# Generated by Django 5.1.4 on 2025-01-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='cover',
        ),
    ]
