# Generated by Django 5.1.4 on 2025-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_portal_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='banner',
            field=models.ImageField(blank=True, default='portal/default-banner.png', null=True, upload_to='portal/banner/'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='avatar',
            field=models.ImageField(blank=True, default='portal/default-avatar.png', null=True, upload_to='portal/avatar/'),
        ),
    ]
