# Generated by Django 5.1.4 on 2025-01-24 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_portal_about_alter_portal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
