# Generated by Django 5.1.4 on 2025-01-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
