# Generated by Django 5.1.4 on 2025-02-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_announcement_title_remove_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
