# Generated by Django 5.1.4 on 2025-01-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='widget',
            name='width',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='widget',
            name='z_index',
            field=models.IntegerField(default=1),
        ),
    ]
